# Generated by Django 6.0.2 on 2026-02-12 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playthrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('stage', models.CharField(blank=True, max_length=100, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playthroughs', to='competitions.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playthroughs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playthrough',
                'verbose_name_plural': 'Playthroughs',
            },
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('stage', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_as_left', to='competitions.contestant')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_as_right', to='competitions.contestant')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duels_as_winner', to='competitions.contestant')),
                ('playthrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels', to='gameplay.playthrough')),
            ],
            options={
                'verbose_name': 'Duel',
                'verbose_name_plural': 'Duels',
            },
        ),
    ]
